
["custom text"]
	#Insert the custom title screen text you want here (supports multiple lines)
	text = ["§d· §9§lD§r§9iesel §b§lP§r§bowered §3§lM§r§3odpack §d·", "§fVersion: v1.0.1"]

[versions]
	#Show which version of Minecraft the client is currently running.
	showMcVersion = true
	#Show which version of Minecraft Coder Pack (MCP) the client is running.
	showMcpVersion = false
	#Show which version of Minecraft Forge the client is running.
	showForgeVersion = true
	#Show how many mods are loaded.
	showModsLoaded = true

